<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Endpoint;

class ListIntegrations extends \Jane\OpenApiRuntime\Client\BaseEndpoint implements \Jane\OpenApiRuntime\Client\Psr7Endpoint
{
    /**
     * Returns list of active integrations.
     *
     * @param array $queryParameters {
     *
     *     @var string $app_code
     *     @var string $is_deleted
     * }
     *
     * @param array $headerParameters {
     *
     *     @var int $x-page-size
     *     @var int $x-page
     * }
     */
    public function __construct(array $queryParameters = [], array $headerParameters = [])
    {
        $this->queryParameters = $queryParameters;
        $this->headerParameters = $headerParameters;
    }

    use \Jane\OpenApiRuntime\Client\Psr7EndpointTrait;

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getUri(): string
    {
        return '/int/apps/integrations';
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getQueryOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getQueryOptionsResolver();
        $optionsResolver->setDefined(['app_code', 'is_deleted']);
        $optionsResolver->setRequired([]);
        $optionsResolver->setDefaults(['is_deleted' => '0']);
        $optionsResolver->setAllowedTypes('app_code', ['string']);
        $optionsResolver->setAllowedTypes('is_deleted', ['string']);

        return $optionsResolver;
    }

    protected function getHeadersOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getHeadersOptionsResolver();
        $optionsResolver->setDefined(['x-page-size', 'x-page']);
        $optionsResolver->setRequired([]);
        $optionsResolver->setDefaults(['x-page-size' => 25, 'x-page' => 1]);
        $optionsResolver->setAllowedTypes('x-page-size', ['int']);
        $optionsResolver->setAllowedTypes('x-page', ['int']);

        return $optionsResolver;
    }

    /**
     * {@inheritdoc}
     *
     * @throws \Afosto\Sdk\Exception\ListIntegrationsBadRequestException
     * @throws \Afosto\Sdk\Exception\ListIntegrationsUnauthorizedException
     * @throws \Afosto\Sdk\Exception\ListIntegrationsForbiddenException
     * @throws \Afosto\Sdk\Exception\ListIntegrationsNotFoundException
     * @throws \Afosto\Sdk\Exception\ListIntegrationsInternalServerErrorException
     * @throws \Afosto\Sdk\Exception\ListIntegrationsServiceUnavailableException
     *
     * @return \Afosto\Sdk\Model\IntIntegration[]|null
     */
    protected function transformResponseBody(string $body, int $status, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType)
    {
        if (200 === $status) {
            return $serializer->deserialize($body, 'Afosto\\Sdk\\Model\\IntIntegration[]', 'json');
        }
        if (400 === $status) {
            throw new \Afosto\Sdk\Exception\ListIntegrationsBadRequestException($serializer->deserialize($body, 'Afosto\\Sdk\\Model\\Error', 'json'));
        }
        if (401 === $status) {
            throw new \Afosto\Sdk\Exception\ListIntegrationsUnauthorizedException($serializer->deserialize($body, 'Afosto\\Sdk\\Model\\Error', 'json'));
        }
        if (403 === $status) {
            throw new \Afosto\Sdk\Exception\ListIntegrationsForbiddenException($serializer->deserialize($body, 'Afosto\\Sdk\\Model\\Error', 'json'));
        }
        if (404 === $status) {
            throw new \Afosto\Sdk\Exception\ListIntegrationsNotFoundException($serializer->deserialize($body, 'Afosto\\Sdk\\Model\\Error', 'json'));
        }
        if (500 === $status) {
            throw new \Afosto\Sdk\Exception\ListIntegrationsInternalServerErrorException($serializer->deserialize($body, 'Afosto\\Sdk\\Model\\Error', 'json'));
        }
        if (503 === $status) {
            throw new \Afosto\Sdk\Exception\ListIntegrationsServiceUnavailableException($serializer->deserialize($body, 'Afosto\\Sdk\\Model\\Error', 'json'));
        }
    }
}
