<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Normalizer;

use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class OdrPointOpeningsItemNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return 'Afosto\\Sdk\\Model\\OdrPointOpeningsItem' === $type;
    }

    public function supportsNormalization($data, $format = null)
    {
        return is_object($data) && 'Afosto\\Sdk\\Model\\OdrPointOpeningsItem' === get_class($data);
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            return null;
        }
        $object = new \Afosto\Sdk\Model\OdrPointOpeningsItem();
        if (property_exists($data, 'weekday') && null !== $data->{'weekday'}) {
            $object->setWeekday($data->{'weekday'});
        }
        if (property_exists($data, 'windows') && null !== $data->{'windows'}) {
            $values = [];
            foreach ($data->{'windows'} as $value) {
                $values[] = $this->denormalizer->denormalize($value, 'Afosto\\Sdk\\Model\\OdrPointOpeningsItemWindowsItem', 'json', $context);
            }
            $object->setWindows($values);
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getWeekday()) {
            $data->{'weekday'} = $object->getWeekday();
        }
        if (null !== $object->getWindows()) {
            $values = [];
            foreach ($object->getWindows() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $data->{'windows'} = $values;
        }

        return $data;
    }
}
