<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Normalizer;

use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class PkrShipmentItemsItemImageThumbnailsNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return 'Afosto\\Sdk\\Model\\PkrShipmentItemsItemImageThumbnails' === $type;
    }

    public function supportsNormalization($data, $format = null)
    {
        return 'Afosto\\Sdk\\Model\\PkrShipmentItemsItemImageThumbnails' === get_class($data);
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            return null;
        }
        $object = new \Afosto\Sdk\Model\PkrShipmentItemsItemImageThumbnails();
        if (property_exists($data, '50') && null !== $data->{'50'}) {
            $object->set50($data->{'50'});
        }
        if (property_exists($data, '100') && null !== $data->{'100'}) {
            $object->set100($data->{'100'});
        }
        if (property_exists($data, '200') && null !== $data->{'200'}) {
            $object->set200($data->{'200'});
        }
        if (property_exists($data, '400') && null !== $data->{'400'}) {
            $object->set400($data->{'400'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->get50()) {
            $data->{'50'} = $object->get50();
        }
        if (null !== $object->get100()) {
            $data->{'100'} = $object->get100();
        }
        if (null !== $object->get200()) {
            $data->{'200'} = $object->get200();
        }
        if (null !== $object->get400()) {
            $data->{'400'} = $object->get400();
        }

        return $data;
    }
}
