<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Normalizer;

use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class SplJobModelNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Afosto\\Sdk\\Model\\SplJobModel';
    }

    public function supportsNormalization($data, $format = null)
    {
        return get_class($data) === 'Afosto\\Sdk\\Model\\SplJobModel';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            return null;
        }
        $object = new \Afosto\Sdk\Model\SplJobModel();
        if (property_exists($data, 'job') && $data->{'job'} !== null) {
            $object->setJob($data->{'job'});
        }
        if (property_exists($data, 'tag') && $data->{'tag'} !== null) {
            $object->setTag($data->{'tag'});
        }
        if (property_exists($data, 'description') && $data->{'description'} !== null) {
            $object->setDescription($data->{'description'});
        }
        if (property_exists($data, 'reference') && $data->{'reference'} !== null) {
            $object->setReference($data->{'reference'});
        }
        if (property_exists($data, 'hub_id') && $data->{'hub_id'} !== null) {
            $object->setHubId($data->{'hub_id'});
        }
        if (property_exists($data, 'schedule_at') && $data->{'schedule_at'} !== null) {
            $object->setScheduleAt(\DateTime::createFromFormat("Y-m-d\TH:i:sP", $data->{'schedule_at'}));
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getJob()) {
            $data->{'job'} = $object->getJob();
        }
        if (null !== $object->getTag()) {
            $data->{'tag'} = $object->getTag();
        }
        if (null !== $object->getDescription()) {
            $data->{'description'} = $object->getDescription();
        }
        if (null !== $object->getReference()) {
            $data->{'reference'} = $object->getReference();
        }
        if (null !== $object->getHubId()) {
            $data->{'hub_id'} = $object->getHubId();
        }
        if (null !== $object->getScheduleAt()) {
            $data->{'schedule_at'} = $object->getScheduleAt()->format("Y-m-d\TH:i:sP");
        }

        return $data;
    }
}
