<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class CatGroupCreate
{
    /**
     * @var string
     */
    protected $name;
    /**
     * True when prices are stored including taxes.
     *
     * @var bool
     */
    protected $isIncludingVat;
    /**
     * @var string
     */
    protected $currency;
    /**
     * @var mixed
     */
    protected $metadata;

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * True when prices are stored including taxes.
     *
     * @return bool|null
     */
    public function getIsIncludingVat(): ?bool
    {
        return $this->isIncludingVat;
    }

    /**
     * True when prices are stored including taxes.
     *
     * @param bool|null $isIncludingVat
     *
     * @return self
     */
    public function setIsIncludingVat(?bool $isIncludingVat): self
    {
        $this->isIncludingVat = $isIncludingVat;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * @param string|null $currency
     *
     * @return self
     */
    public function setCurrency(?string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * @param mixed $metadata
     *
     * @return self
     */
    public function setMetadata($metadata): self
    {
        $this->metadata = $metadata;

        return $this;
    }
}
