<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class CntDatePostResponse200
{
    /**
     * @var int
     */
    protected $epoch;
    /**
     * @var \DateTime
     */
    protected $formatted;

    public function getEpoch(): ?int
    {
        return $this->epoch;
    }

    public function setEpoch(?int $epoch): self
    {
        $this->epoch = $epoch;

        return $this;
    }

    public function getFormatted(): ?\DateTime
    {
        return $this->formatted;
    }

    public function setFormatted(?\DateTime $formatted): self
    {
        $this->formatted = $formatted;

        return $this;
    }
}
