<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class CntHtmlToPdfRequestSize
{
    /**
     * @var string
     */
    protected $predefined;
    /**
     * Size in mm.
     *
     * @var int
     */
    protected $width;
    /**
     * Size in mm.
     *
     * @var int
     */
    protected $height;

    /**
     * @return string|null
     */
    public function getPredefined(): ?string
    {
        return $this->predefined;
    }

    /**
     * @param string|null $predefined
     *
     * @return self
     */
    public function setPredefined(?string $predefined): self
    {
        $this->predefined = $predefined;

        return $this;
    }

    /**
     * Size in mm.
     *
     * @return int|null
     */
    public function getWidth(): ?int
    {
        return $this->width;
    }

    /**
     * Size in mm.
     *
     * @param int|null $width
     *
     * @return self
     */
    public function setWidth(?int $width): self
    {
        $this->width = $width;

        return $this;
    }

    /**
     * Size in mm.
     *
     * @return int|null
     */
    public function getHeight(): ?int
    {
        return $this->height;
    }

    /**
     * Size in mm.
     *
     * @param int|null $height
     *
     * @return self
     */
    public function setHeight(?int $height): self
    {
        $this->height = $height;

        return $this;
    }
}
