<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class IamType
{
    /**
     * @var string
     */
    protected $code;
    /**
     * @var string
     */
    protected $unit;
    /**
     * @var string
     */
    protected $processableAs;
    /**
     * @var string
     */
    protected $filter;

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(?string $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    public function getProcessableAs(): ?string
    {
        return $this->processableAs;
    }

    public function setProcessableAs(?string $processableAs): self
    {
        $this->processableAs = $processableAs;

        return $this;
    }

    public function getFilter(): ?string
    {
        return $this->filter;
    }

    public function setFilter(?string $filter): self
    {
        $this->filter = $filter;

        return $this;
    }
}
