<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class LcsListedHandlingList
{
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $number;
    /**
     * @var string
     */
    protected $sub;
    /**
     * @var string
     */
    protected $locationId;
    /**
     * @var string[]
     */
    protected $shipments;
    /**
     * @var bool
     */
    protected $isOutbound;
    /**
     * @var bool
     */
    protected $isInProgress;
    /**
     * @var bool
     */
    protected $isOnHold;
    /**
     * @var bool
     */
    protected $isCancelled;
    /**
     * @var bool
     */
    protected $isFinished;
    /**
     * @var \DateTime
     */
    protected $startedAt;
    /**
     * @var \DateTime
     */
    protected $finishedAt;
    /**
     * @var \DateTime
     */
    protected $dueAt;
    /**
     * @var LcsShipmentItem[]
     */
    protected $items;
    /**
     * @var \DateTime
     */
    protected $createdAt;
    /**
     * @var \DateTime
     */
    protected $updatedAt;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(?string $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getSub(): ?string
    {
        return $this->sub;
    }

    public function setSub(?string $sub): self
    {
        $this->sub = $sub;

        return $this;
    }

    public function getLocationId(): ?string
    {
        return $this->locationId;
    }

    public function setLocationId(?string $locationId): self
    {
        $this->locationId = $locationId;

        return $this;
    }

    /**
     * @return string[]|null
     */
    public function getShipments(): ?array
    {
        return $this->shipments;
    }

    /**
     * @param string[]|null $shipments
     */
    public function setShipments(?array $shipments): self
    {
        $this->shipments = $shipments;

        return $this;
    }

    public function getIsOutbound(): ?bool
    {
        return $this->isOutbound;
    }

    public function setIsOutbound(?bool $isOutbound): self
    {
        $this->isOutbound = $isOutbound;

        return $this;
    }

    public function getIsInProgress(): ?bool
    {
        return $this->isInProgress;
    }

    public function setIsInProgress(?bool $isInProgress): self
    {
        $this->isInProgress = $isInProgress;

        return $this;
    }

    public function getIsOnHold(): ?bool
    {
        return $this->isOnHold;
    }

    public function setIsOnHold(?bool $isOnHold): self
    {
        $this->isOnHold = $isOnHold;

        return $this;
    }

    public function getIsCancelled(): ?bool
    {
        return $this->isCancelled;
    }

    public function setIsCancelled(?bool $isCancelled): self
    {
        $this->isCancelled = $isCancelled;

        return $this;
    }

    public function getIsFinished(): ?bool
    {
        return $this->isFinished;
    }

    public function setIsFinished(?bool $isFinished): self
    {
        $this->isFinished = $isFinished;

        return $this;
    }

    public function getStartedAt(): ?\DateTime
    {
        return $this->startedAt;
    }

    public function setStartedAt(?\DateTime $startedAt): self
    {
        $this->startedAt = $startedAt;

        return $this;
    }

    public function getFinishedAt(): ?\DateTime
    {
        return $this->finishedAt;
    }

    public function setFinishedAt(?\DateTime $finishedAt): self
    {
        $this->finishedAt = $finishedAt;

        return $this;
    }

    public function getDueAt(): ?\DateTime
    {
        return $this->dueAt;
    }

    public function setDueAt(?\DateTime $dueAt): self
    {
        $this->dueAt = $dueAt;

        return $this;
    }

    /**
     * @return LcsShipmentItem[]|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * @param LcsShipmentItem[]|null $items
     */
    public function setItems(?array $items): self
    {
        $this->items = $items;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}
