<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class LcsLocationPosition
{
    /**
     * @var string
     */
    protected $code;
    /**
     * @var int
     */
    protected $sorting;
    /**
     * @var LcsLocationSku[]
     */
    protected $skus;
    /**
     * @var \DateTime
     */
    protected $createdAt;

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getSorting(): ?int
    {
        return $this->sorting;
    }

    public function setSorting(?int $sorting): self
    {
        $this->sorting = $sorting;

        return $this;
    }

    /**
     * @return LcsLocationSku[]|null
     */
    public function getSkus(): ?array
    {
        return $this->skus;
    }

    /**
     * @param LcsLocationSku[]|null $skus
     */
    public function setSkus(?array $skus): self
    {
        $this->skus = $skus;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}
