<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class LcsParcelLabel
{
    /**
     * @var string
     */
    protected $fileId;
    /**
     * @var string
     */
    protected $reference;
    /**
     * @var string
     */
    protected $labelText;
    /**
     * @var \DateTime
     */
    protected $requestedAt;

    /**
     * @return string|null
     */
    public function getFileId(): ?string
    {
        return $this->fileId;
    }

    /**
     * @param string|null $fileId
     *
     * @return self
     */
    public function setFileId(?string $fileId): self
    {
        $this->fileId = $fileId;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * @param string|null $reference
     *
     * @return self
     */
    public function setReference(?string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLabelText(): ?string
    {
        return $this->labelText;
    }

    /**
     * @param string|null $labelText
     *
     * @return self
     */
    public function setLabelText(?string $labelText): self
    {
        $this->labelText = $labelText;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getRequestedAt(): ?\DateTime
    {
        return $this->requestedAt;
    }

    /**
     * @param \DateTime|null $requestedAt
     *
     * @return self
     */
    public function setRequestedAt(?\DateTime $requestedAt): self
    {
        $this->requestedAt = $requestedAt;

        return $this;
    }
}
