<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class LcsShipmentAddressingCarrier
{
    /**
     * @var bool
     */
    protected $isCarrierLocation;
    /**
     * @var string
     */
    protected $carrierLocationReference;

    public function getIsCarrierLocation(): ?bool
    {
        return $this->isCarrierLocation;
    }

    public function setIsCarrierLocation(?bool $isCarrierLocation): self
    {
        $this->isCarrierLocation = $isCarrierLocation;

        return $this;
    }

    public function getCarrierLocationReference(): ?string
    {
        return $this->carrierLocationReference;
    }

    public function setCarrierLocationReference(?string $carrierLocationReference): self
    {
        $this->carrierLocationReference = $carrierLocationReference;

        return $this;
    }
}
