<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class LcsShipmentDetailsAddressingTo
{
    /**
     * @var string
     */
    protected $entityType;
    /**
     * @var string
     */
    protected $entityId;
    /**
     * @var LcsShipmentDetailsAddressingToCarrier
     */
    protected $carrier;
    /**
     * @var LcsAddress
     */
    protected $address;

    /**
     * @return string|null
     */
    public function getEntityType(): ?string
    {
        return $this->entityType;
    }

    /**
     * @param string|null $entityType
     *
     * @return self
     */
    public function setEntityType(?string $entityType): self
    {
        $this->entityType = $entityType;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getEntityId(): ?string
    {
        return $this->entityId;
    }

    /**
     * @param string|null $entityId
     *
     * @return self
     */
    public function setEntityId(?string $entityId): self
    {
        $this->entityId = $entityId;

        return $this;
    }

    /**
     * @return LcsShipmentDetailsAddressingToCarrier|null
     */
    public function getCarrier(): ?LcsShipmentDetailsAddressingToCarrier
    {
        return $this->carrier;
    }

    /**
     * @param LcsShipmentDetailsAddressingToCarrier|null $carrier
     *
     * @return self
     */
    public function setCarrier(?LcsShipmentDetailsAddressingToCarrier $carrier): self
    {
        $this->carrier = $carrier;

        return $this;
    }

    /**
     * @return LcsAddress|null
     */
    public function getAddress(): ?LcsAddress
    {
        return $this->address;
    }

    /**
     * @param LcsAddress|null $address
     *
     * @return self
     */
    public function setAddress(?LcsAddress $address): self
    {
        $this->address = $address;

        return $this;
    }
}
