<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrCalculationOrderItem
{
    /**
     * @var string
     */
    protected $id;
    /**
     * @var bool
     */
    protected $isInvoiced;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getIsInvoiced(): ?bool
    {
        return $this->isInvoiced;
    }

    public function setIsInvoiced(?bool $isInvoiced): self
    {
        $this->isInvoiced = $isInvoiced;

        return $this;
    }
}
