<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrCalculationItem
{
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $reference;
    /**
     * @var string
     */
    protected $sku;
    /**
     * @var string
     */
    protected $description;
    /**
     * @var string
     */
    protected $type;
    /**
     * @var int
     */
    protected $amount;
    /**
     * @var bool
     */
    protected $isDiscounted;
    /**
     * @var int
     */
    protected $quantity;
    /**
     * @var int
     */
    protected $subtotal;
    /**
     * @var OdrCalculationAdjustment[]
     */
    protected $adjustments;
    /**
     * @var int
     */
    protected $vatPercentage;
    /**
     * @var int
     */
    protected $total;
    /**
     * @var int
     */
    protected $totalRevenue;
    /**
     * @var OdrCalculationStackItem[]
     */
    protected $stackItems;

    /**
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param string|null $id
     *
     * @return self
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * @param string|null $reference
     *
     * @return self
     */
    public function setReference(?string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSku(): ?string
    {
        return $this->sku;
    }

    /**
     * @param string|null $sku
     *
     * @return self
     */
    public function setSku(?string $sku): self
    {
        $this->sku = $sku;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string|null $description
     *
     * @return self
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * @param string|null $type
     *
     * @return self
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getAmount(): ?int
    {
        return $this->amount;
    }

    /**
     * @param int|null $amount
     *
     * @return self
     */
    public function setAmount(?int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsDiscounted(): ?bool
    {
        return $this->isDiscounted;
    }

    /**
     * @param bool|null $isDiscounted
     *
     * @return self
     */
    public function setIsDiscounted(?bool $isDiscounted): self
    {
        $this->isDiscounted = $isDiscounted;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * @param int|null $quantity
     *
     * @return self
     */
    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getSubtotal(): ?int
    {
        return $this->subtotal;
    }

    /**
     * @param int|null $subtotal
     *
     * @return self
     */
    public function setSubtotal(?int $subtotal): self
    {
        $this->subtotal = $subtotal;

        return $this;
    }

    /**
     * @return OdrCalculationAdjustment[]|null
     */
    public function getAdjustments(): ?array
    {
        return $this->adjustments;
    }

    /**
     * @param OdrCalculationAdjustment[]|null $adjustments
     *
     * @return self
     */
    public function setAdjustments(?array $adjustments): self
    {
        $this->adjustments = $adjustments;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getVatPercentage(): ?int
    {
        return $this->vatPercentage;
    }

    /**
     * @param int|null $vatPercentage
     *
     * @return self
     */
    public function setVatPercentage(?int $vatPercentage): self
    {
        $this->vatPercentage = $vatPercentage;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getTotal(): ?int
    {
        return $this->total;
    }

    /**
     * @param int|null $total
     *
     * @return self
     */
    public function setTotal(?int $total): self
    {
        $this->total = $total;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getTotalRevenue(): ?int
    {
        return $this->totalRevenue;
    }

    /**
     * @param int|null $totalRevenue
     *
     * @return self
     */
    public function setTotalRevenue(?int $totalRevenue): self
    {
        $this->totalRevenue = $totalRevenue;

        return $this;
    }

    /**
     * @return OdrCalculationStackItem[]|null
     */
    public function getStackItems(): ?array
    {
        return $this->stackItems;
    }

    /**
     * @param OdrCalculationStackItem[]|null $stackItems
     *
     * @return self
     */
    public function setStackItems(?array $stackItems): self
    {
        $this->stackItems = $stackItems;

        return $this;
    }
}
