<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrGetSessionResponse
{
    /**
     * @var string
     */
    protected $expiresAt;
    /**
     * @var OdrContact
     */
    protected $contact;
    /**
     * @var OdrAddress
     */
    protected $billingAddress;
    /**
     * @var OdrAddress
     */
    protected $shippingAddress;
    /**
     * @var OdrGetSessionDeliveryWindow
     */
    protected $window;
    /**
     * @var float
     */
    protected $spid;

    public function getExpiresAt(): ?string
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(?string $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }

    public function getContact(): ?OdrContact
    {
        return $this->contact;
    }

    public function setContact(?OdrContact $contact): self
    {
        $this->contact = $contact;

        return $this;
    }

    public function getBillingAddress(): ?OdrAddress
    {
        return $this->billingAddress;
    }

    public function setBillingAddress(?OdrAddress $billingAddress): self
    {
        $this->billingAddress = $billingAddress;

        return $this;
    }

    public function getShippingAddress(): ?OdrAddress
    {
        return $this->shippingAddress;
    }

    public function setShippingAddress(?OdrAddress $shippingAddress): self
    {
        $this->shippingAddress = $shippingAddress;

        return $this;
    }

    public function getWindow(): ?OdrGetSessionDeliveryWindow
    {
        return $this->window;
    }

    public function setWindow(?OdrGetSessionDeliveryWindow $window): self
    {
        $this->window = $window;

        return $this;
    }

    public function getSpid(): ?float
    {
        return $this->spid;
    }

    public function setSpid(?float $spid): self
    {
        $this->spid = $spid;

        return $this;
    }
}
