<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrInvoiceModel
{
    /**
     * @var string
     */
    protected $country;
    /**
     * @var OdrInvoiceItemModel[]
     */
    protected $items;
    /**
     * @var OdrAdjustment[]
     */
    protected $adjustments;
    /**
     * @var string
     */
    protected $clientId;
    /**
     * @var OdrStackReference
     */
    protected $stackReference;
    /**
     * @var string
     */
    protected $customerId;
    /**
     * @var string
     */
    protected $addressSetId;
    /**
     * @var string
     */
    protected $paymentMethodId;
    /**
     * @var string[]
     */
    protected $coupons;
    /**
     * @var string[]
     */
    protected $routes;
    /**
     * @var mixed
     */
    protected $metadata;

    /**
     * @return string|null
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * @param string|null $country
     *
     * @return self
     */
    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return OdrInvoiceItemModel[]|null
     */
    public function getItems(): ?array
    {
        return $this->items;
    }

    /**
     * @param OdrInvoiceItemModel[]|null $items
     *
     * @return self
     */
    public function setItems(?array $items): self
    {
        $this->items = $items;

        return $this;
    }

    /**
     * @return OdrAdjustment[]|null
     */
    public function getAdjustments(): ?array
    {
        return $this->adjustments;
    }

    /**
     * @param OdrAdjustment[]|null $adjustments
     *
     * @return self
     */
    public function setAdjustments(?array $adjustments): self
    {
        $this->adjustments = $adjustments;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getClientId(): ?string
    {
        return $this->clientId;
    }

    /**
     * @param string|null $clientId
     *
     * @return self
     */
    public function setClientId(?string $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    /**
     * @return OdrStackReference|null
     */
    public function getStackReference(): ?OdrStackReference
    {
        return $this->stackReference;
    }

    /**
     * @param OdrStackReference|null $stackReference
     *
     * @return self
     */
    public function setStackReference(?OdrStackReference $stackReference): self
    {
        $this->stackReference = $stackReference;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCustomerId(): ?string
    {
        return $this->customerId;
    }

    /**
     * @param string|null $customerId
     *
     * @return self
     */
    public function setCustomerId(?string $customerId): self
    {
        $this->customerId = $customerId;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getAddressSetId(): ?string
    {
        return $this->addressSetId;
    }

    /**
     * @param string|null $addressSetId
     *
     * @return self
     */
    public function setAddressSetId(?string $addressSetId): self
    {
        $this->addressSetId = $addressSetId;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPaymentMethodId(): ?string
    {
        return $this->paymentMethodId;
    }

    /**
     * @param string|null $paymentMethodId
     *
     * @return self
     */
    public function setPaymentMethodId(?string $paymentMethodId): self
    {
        $this->paymentMethodId = $paymentMethodId;

        return $this;
    }

    /**
     * @return string[]|null
     */
    public function getCoupons(): ?array
    {
        return $this->coupons;
    }

    /**
     * @param string[]|null $coupons
     *
     * @return self
     */
    public function setCoupons(?array $coupons): self
    {
        $this->coupons = $coupons;

        return $this;
    }

    /**
     * @return string[]|null
     */
    public function getRoutes(): ?array
    {
        return $this->routes;
    }

    /**
     * @param string[]|null $routes
     *
     * @return self
     */
    public function setRoutes(?array $routes): self
    {
        $this->routes = $routes;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * @param mixed $metadata
     *
     * @return self
     */
    public function setMetadata($metadata): self
    {
        $this->metadata = $metadata;

        return $this;
    }
}
