<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrInvoiceListItem
{
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $version;
    /**
     * @var string
     */
    protected $number;
    /**
     * @var int
     */
    protected $count;
    /**
     * @var int
     */
    protected $subtotal;
    /**
     * @var OdrInvoiceAdjustmentResponse[]
     */
    protected $adjustments;
    /**
     * @var int
     */
    protected $total;
    /**
     * @var OdrVatResult[]
     */
    protected $vat;
    /**
     * @var string
     */
    protected $currency;
    /**
     * @var OdrContact
     */
    protected $customer;
    /**
     * @var OdrContact
     */
    protected $vendor;
    /**
     * @var bool
     */
    protected $isIncludingVat;
    /**
     * @var bool
     */
    protected $isVatShifted;
    /**
     * @var bool
     */
    protected $isConcept;
    /**
     * @var bool
     */
    protected $isPaid;
    /**
     * @var string
     */
    protected $clientId;
    /**
     * @var string
     */
    protected $fileId;
    /**
     * @var mixed
     */
    protected $metadata;
    /**
     * @var \DateTime
     */
    protected $pricingAt;
    /**
     * @var \DateTime
     */
    protected $invoicedAt;
    /**
     * @var \DateTime
     */
    protected $paidAt;
    /**
     * @var \DateTime
     */
    protected $createdAt;
    /**
     * @var \DateTime
     */
    protected $updatedAt;

    /**
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param string|null $id
     *
     * @return self
     */
    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * @param string|null $version
     *
     * @return self
     */
    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * @param string|null $number
     *
     * @return self
     */
    public function setNumber(?string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getCount(): ?int
    {
        return $this->count;
    }

    /**
     * @param int|null $count
     *
     * @return self
     */
    public function setCount(?int $count): self
    {
        $this->count = $count;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getSubtotal(): ?int
    {
        return $this->subtotal;
    }

    /**
     * @param int|null $subtotal
     *
     * @return self
     */
    public function setSubtotal(?int $subtotal): self
    {
        $this->subtotal = $subtotal;

        return $this;
    }

    /**
     * @return OdrInvoiceAdjustmentResponse[]|null
     */
    public function getAdjustments(): ?array
    {
        return $this->adjustments;
    }

    /**
     * @param OdrInvoiceAdjustmentResponse[]|null $adjustments
     *
     * @return self
     */
    public function setAdjustments(?array $adjustments): self
    {
        $this->adjustments = $adjustments;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getTotal(): ?int
    {
        return $this->total;
    }

    /**
     * @param int|null $total
     *
     * @return self
     */
    public function setTotal(?int $total): self
    {
        $this->total = $total;

        return $this;
    }

    /**
     * @return OdrVatResult[]|null
     */
    public function getVat(): ?array
    {
        return $this->vat;
    }

    /**
     * @param OdrVatResult[]|null $vat
     *
     * @return self
     */
    public function setVat(?array $vat): self
    {
        $this->vat = $vat;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * @param string|null $currency
     *
     * @return self
     */
    public function setCurrency(?string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * @return OdrContact|null
     */
    public function getCustomer(): ?OdrContact
    {
        return $this->customer;
    }

    /**
     * @param OdrContact|null $customer
     *
     * @return self
     */
    public function setCustomer(?OdrContact $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return OdrContact|null
     */
    public function getVendor(): ?OdrContact
    {
        return $this->vendor;
    }

    /**
     * @param OdrContact|null $vendor
     *
     * @return self
     */
    public function setVendor(?OdrContact $vendor): self
    {
        $this->vendor = $vendor;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsIncludingVat(): ?bool
    {
        return $this->isIncludingVat;
    }

    /**
     * @param bool|null $isIncludingVat
     *
     * @return self
     */
    public function setIsIncludingVat(?bool $isIncludingVat): self
    {
        $this->isIncludingVat = $isIncludingVat;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsVatShifted(): ?bool
    {
        return $this->isVatShifted;
    }

    /**
     * @param bool|null $isVatShifted
     *
     * @return self
     */
    public function setIsVatShifted(?bool $isVatShifted): self
    {
        $this->isVatShifted = $isVatShifted;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsConcept(): ?bool
    {
        return $this->isConcept;
    }

    /**
     * @param bool|null $isConcept
     *
     * @return self
     */
    public function setIsConcept(?bool $isConcept): self
    {
        $this->isConcept = $isConcept;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsPaid(): ?bool
    {
        return $this->isPaid;
    }

    /**
     * @param bool|null $isPaid
     *
     * @return self
     */
    public function setIsPaid(?bool $isPaid): self
    {
        $this->isPaid = $isPaid;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getClientId(): ?string
    {
        return $this->clientId;
    }

    /**
     * @param string|null $clientId
     *
     * @return self
     */
    public function setClientId(?string $clientId): self
    {
        $this->clientId = $clientId;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFileId(): ?string
    {
        return $this->fileId;
    }

    /**
     * @param string|null $fileId
     *
     * @return self
     */
    public function setFileId(?string $fileId): self
    {
        $this->fileId = $fileId;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * @param mixed $metadata
     *
     * @return self
     */
    public function setMetadata($metadata): self
    {
        $this->metadata = $metadata;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getPricingAt(): ?\DateTime
    {
        return $this->pricingAt;
    }

    /**
     * @param \DateTime|null $pricingAt
     *
     * @return self
     */
    public function setPricingAt(?\DateTime $pricingAt): self
    {
        $this->pricingAt = $pricingAt;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getInvoicedAt(): ?\DateTime
    {
        return $this->invoicedAt;
    }

    /**
     * @param \DateTime|null $invoicedAt
     *
     * @return self
     */
    public function setInvoicedAt(?\DateTime $invoicedAt): self
    {
        $this->invoicedAt = $invoicedAt;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getPaidAt(): ?\DateTime
    {
        return $this->paidAt;
    }

    /**
     * @param \DateTime|null $paidAt
     *
     * @return self
     */
    public function setPaidAt(?\DateTime $paidAt): self
    {
        $this->paidAt = $paidAt;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime|null $createdAt
     *
     * @return self
     */
    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime|null $updatedAt
     *
     * @return self
     */
    public function setUpdatedAt(?\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}
