<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrInvoiceSettings
{
    /**
     * @var OdrInvoiceSettingsBilling
     */
    protected $billing;
    /**
     * @var OdrInvoiceSettingsShipping
     */
    protected $shipping;

    public function getBilling(): ?OdrInvoiceSettingsBilling
    {
        return $this->billing;
    }

    public function setBilling(?OdrInvoiceSettingsBilling $billing): self
    {
        $this->billing = $billing;

        return $this;
    }

    public function getShipping(): ?OdrInvoiceSettingsShipping
    {
        return $this->shipping;
    }

    public function setShipping(?OdrInvoiceSettingsShipping $shipping): self
    {
        $this->shipping = $shipping;

        return $this;
    }
}
