<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrOrganisationModel
{
    /**
     * The name of the recipient, firm, or company at this address (optional).
     *
     * @var string
     */
    protected $name;
    /**
     * @var OdrVatRegistrationModel[]
     */
    protected $registrations;
    /**
     * @var OdrAddressModel
     */
    protected $address;
    /**
     * @var string
     */
    protected $cocNumber;

    /**
     * The name of the recipient, firm, or company at this address (optional).
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * The name of the recipient, firm, or company at this address (optional).
     *
     * @param string|null $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return OdrVatRegistrationModel[]|null
     */
    public function getRegistrations(): ?array
    {
        return $this->registrations;
    }

    /**
     * @param OdrVatRegistrationModel[]|null $registrations
     *
     * @return self
     */
    public function setRegistrations(?array $registrations): self
    {
        $this->registrations = $registrations;

        return $this;
    }

    /**
     * @return OdrAddressModel|null
     */
    public function getAddress(): ?OdrAddressModel
    {
        return $this->address;
    }

    /**
     * @param OdrAddressModel|null $address
     *
     * @return self
     */
    public function setAddress(?OdrAddressModel $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCocNumber(): ?string
    {
        return $this->cocNumber;
    }

    /**
     * @param string|null $cocNumber
     *
     * @return self
     */
    public function setCocNumber(?string $cocNumber): self
    {
        $this->cocNumber = $cocNumber;

        return $this;
    }
}
