<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrOrdersIdFlowPutBody
{
    /**
     * @var string
     */
    protected $code;
    /**
     * @var OdrOrdersIdFlowPutBodyActionsItem[]
     */
    protected $actions;

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * @return OdrOrdersIdFlowPutBodyActionsItem[]|null
     */
    public function getActions(): ?array
    {
        return $this->actions;
    }

    /**
     * @param OdrOrdersIdFlowPutBodyActionsItem[]|null $actions
     */
    public function setActions(?array $actions): self
    {
        $this->actions = $actions;

        return $this;
    }
}
