<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrOrderSettingsShipping
{
    /**
     * @var string
     */
    protected $addressId;
    /**
     * @var string
     */
    protected $methodId;
    /**
     * @var string
     */
    protected $spid;
    /**
     * @var OdrOrderSettingsShippingWindow
     */
    protected $window;
    /**
     * @var bool
     */
    protected $isSplitAllowed;

    public function getAddressId(): ?string
    {
        return $this->addressId;
    }

    public function setAddressId(?string $addressId): self
    {
        $this->addressId = $addressId;

        return $this;
    }

    public function getMethodId(): ?string
    {
        return $this->methodId;
    }

    public function setMethodId(?string $methodId): self
    {
        $this->methodId = $methodId;

        return $this;
    }

    public function getSpid(): ?string
    {
        return $this->spid;
    }

    public function setSpid(?string $spid): self
    {
        $this->spid = $spid;

        return $this;
    }

    public function getWindow(): ?OdrOrderSettingsShippingWindow
    {
        return $this->window;
    }

    public function setWindow(?OdrOrderSettingsShippingWindow $window): self
    {
        $this->window = $window;

        return $this;
    }

    public function getIsSplitAllowed(): ?bool
    {
        return $this->isSplitAllowed;
    }

    public function setIsSplitAllowed(?bool $isSplitAllowed): self
    {
        $this->isSplitAllowed = $isSplitAllowed;

        return $this;
    }
}
