<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrSelectSessionOrganisationRequest
{
    /**
     * @var string
     */
    protected $organisationId;

    public function getOrganisationId(): ?string
    {
        return $this->organisationId;
    }

    public function setOrganisationId(?string $organisationId): self
    {
        $this->organisationId = $organisationId;

        return $this;
    }
}
