<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrSelectSessionShippingPointRequest
{
    /**
     * @var string
     */
    protected $spid;

    public function getSpid(): ?string
    {
        return $this->spid;
    }

    public function setSpid(?string $spid): self
    {
        $this->spid = $spid;

        return $this;
    }
}
