<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OdrSelectSessionBillingRequestContact
{
    /**
     * @var bool
     */
    protected $primary;
    /**
     * @var bool
     */
    protected $secondary;

    public function getPrimary(): ?bool
    {
        return $this->primary;
    }

    public function setPrimary(?bool $primary): self
    {
        $this->primary = $primary;

        return $this;
    }

    public function getSecondary(): ?bool
    {
        return $this->secondary;
    }

    public function setSecondary(?bool $secondary): self
    {
        $this->secondary = $secondary;

        return $this;
    }
}
