<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class OmsCustomerModel
{
    /**
     * @var string
     */
    protected $company;
    /**
     * @var string
     */
    protected $firstName;
    /**
     * @var string
     */
    protected $lastName;
    /**
     * @var string
     */
    protected $lastNamePrefix;
    /**
     * @var bool
     */
    protected $isFemale;
    /**
     * @var \DateTime
     */
    protected $bornAt;
    /**
     * @var string
     */
    protected $phoneNumber;
    /**
     * @var string
     */
    protected $email;
    /**
     * @var OmsAddress[]
     */
    protected $billing;
    /**
     * @var OmsAddress[]
     */
    protected $shipping;
    /**
     * @var string
     */
    protected $groupId;

    /**
     * @return string|null
     */
    public function getCompany(): ?string
    {
        return $this->company;
    }

    /**
     * @param string|null $company
     *
     * @return self
     */
    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * @param string|null $firstName
     *
     * @return self
     */
    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * @param string|null $lastName
     *
     * @return self
     */
    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLastNamePrefix(): ?string
    {
        return $this->lastNamePrefix;
    }

    /**
     * @param string|null $lastNamePrefix
     *
     * @return self
     */
    public function setLastNamePrefix(?string $lastNamePrefix): self
    {
        $this->lastNamePrefix = $lastNamePrefix;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsFemale(): ?bool
    {
        return $this->isFemale;
    }

    /**
     * @param bool|null $isFemale
     *
     * @return self
     */
    public function setIsFemale(?bool $isFemale): self
    {
        $this->isFemale = $isFemale;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getBornAt(): ?\DateTime
    {
        return $this->bornAt;
    }

    /**
     * @param \DateTime|null $bornAt
     *
     * @return self
     */
    public function setBornAt(?\DateTime $bornAt): self
    {
        $this->bornAt = $bornAt;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    /**
     * @param string|null $phoneNumber
     *
     * @return self
     */
    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string|null $email
     *
     * @return self
     */
    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return OmsAddress[]|null
     */
    public function getBilling(): ?array
    {
        return $this->billing;
    }

    /**
     * @param OmsAddress[]|null $billing
     *
     * @return self
     */
    public function setBilling(?array $billing): self
    {
        $this->billing = $billing;

        return $this;
    }

    /**
     * @return OmsAddress[]|null
     */
    public function getShipping(): ?array
    {
        return $this->shipping;
    }

    /**
     * @param OmsAddress[]|null $shipping
     *
     * @return self
     */
    public function setShipping(?array $shipping): self
    {
        $this->shipping = $shipping;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getGroupId(): ?string
    {
        return $this->groupId;
    }

    /**
     * @param string|null $groupId
     *
     * @return self
     */
    public function setGroupId(?string $groupId): self
    {
        $this->groupId = $groupId;

        return $this;
    }
}
