<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class PkrShipmentAddress
{
    /**
     * @var string
     */
    protected $city;
    /**
     * @var string
     */
    protected $company;
    /**
     * @var PkrShipmentAddressCountry
     */
    protected $country;
    /**
     * @var int
     */
    protected $houseNumber;
    /**
     * @var string
     */
    protected $houseNumberSuffix;
    /**
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $region;
    /**
     * @var string
     */
    protected $street;
    /**
     * @var string
     */
    protected $zipCode;

    /**
     * @return string|null
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * @param string|null $city
     *
     * @return self
     */
    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCompany(): ?string
    {
        return $this->company;
    }

    /**
     * @param string|null $company
     *
     * @return self
     */
    public function setCompany(?string $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return PkrShipmentAddressCountry|null
     */
    public function getCountry(): ?PkrShipmentAddressCountry
    {
        return $this->country;
    }

    /**
     * @param PkrShipmentAddressCountry|null $country
     *
     * @return self
     */
    public function setCountry(?PkrShipmentAddressCountry $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getHouseNumber(): ?int
    {
        return $this->houseNumber;
    }

    /**
     * @param int|null $houseNumber
     *
     * @return self
     */
    public function setHouseNumber(?int $houseNumber): self
    {
        $this->houseNumber = $houseNumber;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getHouseNumberSuffix(): ?string
    {
        return $this->houseNumberSuffix;
    }

    /**
     * @param string|null $houseNumberSuffix
     *
     * @return self
     */
    public function setHouseNumberSuffix(?string $houseNumberSuffix): self
    {
        $this->houseNumberSuffix = $houseNumberSuffix;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getRegion(): ?string
    {
        return $this->region;
    }

    /**
     * @param string|null $region
     *
     * @return self
     */
    public function setRegion(?string $region): self
    {
        $this->region = $region;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getStreet(): ?string
    {
        return $this->street;
    }

    /**
     * @param string|null $street
     *
     * @return self
     */
    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    /**
     * @param string|null $zipCode
     *
     * @return self
     */
    public function setZipCode(?string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }
}
