<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class PkrShipmentItemsItemImage
{
    /**
     * @var string
     */
    protected $original;
    /**
     * @var PkrShipmentItemsItemImageThumbnails
     */
    protected $thumbnails;

    /**
     * @return string|null
     */
    public function getOriginal(): ?string
    {
        return $this->original;
    }

    /**
     * @param string|null $original
     *
     * @return self
     */
    public function setOriginal(?string $original): self
    {
        $this->original = $original;

        return $this;
    }

    /**
     * @return PkrShipmentItemsItemImageThumbnails|null
     */
    public function getThumbnails(): ?PkrShipmentItemsItemImageThumbnails
    {
        return $this->thumbnails;
    }

    /**
     * @param PkrShipmentItemsItemImageThumbnails|null $thumbnails
     *
     * @return self
     */
    public function setThumbnails(?PkrShipmentItemsItemImageThumbnails $thumbnails): self
    {
        $this->thumbnails = $thumbnails;

        return $this;
    }
}
