<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class QcqProxyUpdateModel
{
    /**
     * @var QcqRoute[]
     */
    protected $routes;
    /**
     * @var QcqProxyUpdateModelAuth
     */
    protected $auth;
    /**
     * @var QcqProxyUpdateModelOauth
     */
    protected $oauth;

    /**
     * @return QcqRoute[]|null
     */
    public function getRoutes(): ?array
    {
        return $this->routes;
    }

    /**
     * @param QcqRoute[]|null $routes
     */
    public function setRoutes(?array $routes): self
    {
        $this->routes = $routes;

        return $this;
    }

    public function getAuth(): ?QcqProxyUpdateModelAuth
    {
        return $this->auth;
    }

    public function setAuth(?QcqProxyUpdateModelAuth $auth): self
    {
        $this->auth = $auth;

        return $this;
    }

    public function getOauth(): ?QcqProxyUpdateModelOauth
    {
        return $this->oauth;
    }

    public function setOauth(?QcqProxyUpdateModelOauth $oauth): self
    {
        $this->oauth = $oauth;

        return $this;
    }
}
