<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class RelOrganisationUpdateModel
{
    /**
     * The name of the recipient, firm, or company at this address (optional).
     *
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $cocNumber;
    /**
     * @var string
     */
    protected $accountManager;
    /**
     * @var RelVatRegistrationModel[]
     */
    protected $registrations;
    /**
     * @var RelOrganisationPaymentSettings
     */
    protected $paymentSettings;
    /**
     * @var RelOrganisationUpdateModelAddresses
     */
    protected $addresses;
    /**
     * @var RelOrganisationUpdateModelPhoneNumbers
     */
    protected $phoneNumbers;

    /**
     * The name of the recipient, firm, or company at this address (optional).
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * The name of the recipient, firm, or company at this address (optional).
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCocNumber(): ?string
    {
        return $this->cocNumber;
    }

    public function setCocNumber(?string $cocNumber): self
    {
        $this->cocNumber = $cocNumber;

        return $this;
    }

    public function getAccountManager(): ?string
    {
        return $this->accountManager;
    }

    public function setAccountManager(?string $accountManager): self
    {
        $this->accountManager = $accountManager;

        return $this;
    }

    /**
     * @return RelVatRegistrationModel[]|null
     */
    public function getRegistrations(): ?array
    {
        return $this->registrations;
    }

    /**
     * @param RelVatRegistrationModel[]|null $registrations
     */
    public function setRegistrations(?array $registrations): self
    {
        $this->registrations = $registrations;

        return $this;
    }

    public function getPaymentSettings(): ?RelOrganisationPaymentSettings
    {
        return $this->paymentSettings;
    }

    public function setPaymentSettings(?RelOrganisationPaymentSettings $paymentSettings): self
    {
        $this->paymentSettings = $paymentSettings;

        return $this;
    }

    public function getAddresses(): ?RelOrganisationUpdateModelAddresses
    {
        return $this->addresses;
    }

    public function setAddresses(?RelOrganisationUpdateModelAddresses $addresses): self
    {
        $this->addresses = $addresses;

        return $this;
    }

    public function getPhoneNumbers(): ?RelOrganisationUpdateModelPhoneNumbers
    {
        return $this->phoneNumbers;
    }

    public function setPhoneNumbers(?RelOrganisationUpdateModelPhoneNumbers $phoneNumbers): self
    {
        $this->phoneNumbers = $phoneNumbers;

        return $this;
    }
}
