<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class RelOrganisationPaymentSettings
{
    /**
     * @var RelOrganisationPaymentSettingsPostPayment
     */
    protected $postPayment;
    /**
     * @var RelOrganisationPaymentSettingsInvoice
     */
    protected $invoice;

    public function getPostPayment(): ?RelOrganisationPaymentSettingsPostPayment
    {
        return $this->postPayment;
    }

    public function setPostPayment(?RelOrganisationPaymentSettingsPostPayment $postPayment): self
    {
        $this->postPayment = $postPayment;

        return $this;
    }

    public function getInvoice(): ?RelOrganisationPaymentSettingsInvoice
    {
        return $this->invoice;
    }

    public function setInvoice(?RelOrganisationPaymentSettingsInvoice $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }
}
