<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class RelOrganisationPaymentSettingsPostPayment
{
    /**
     * @var int
     */
    protected $spendingLimit;
    /**
     * @var int
     */
    protected $currentDueAmount;
    /**
     * @var int
     */
    protected $dueAfter;
    /**
     * @var string
     */
    protected $iban;

    public function getSpendingLimit(): ?int
    {
        return $this->spendingLimit;
    }

    public function setSpendingLimit(?int $spendingLimit): self
    {
        $this->spendingLimit = $spendingLimit;

        return $this;
    }

    public function getCurrentDueAmount(): ?int
    {
        return $this->currentDueAmount;
    }

    public function setCurrentDueAmount(?int $currentDueAmount): self
    {
        $this->currentDueAmount = $currentDueAmount;

        return $this;
    }

    public function getDueAfter(): ?int
    {
        return $this->dueAfter;
    }

    public function setDueAfter(?int $dueAfter): self
    {
        $this->dueAfter = $dueAfter;

        return $this;
    }

    public function getIban(): ?string
    {
        return $this->iban;
    }

    public function setIban(?string $iban): self
    {
        $this->iban = $iban;

        return $this;
    }
}
