<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class RelOrganisationPaymentSettingsInvoice
{
    /**
     * @var bool
     */
    protected $isExpectedThroughPostMail;
    /**
     * @var bool
     */
    protected $isExpectedThroughEmail;
    /**
     * @var bool
     */
    protected $isExcectedAtDelivery;

    /**
     * @return bool|null
     */
    public function getIsExpectedThroughPostMail(): ?bool
    {
        return $this->isExpectedThroughPostMail;
    }

    /**
     * @param bool|null $isExpectedThroughPostMail
     *
     * @return self
     */
    public function setIsExpectedThroughPostMail(?bool $isExpectedThroughPostMail): self
    {
        $this->isExpectedThroughPostMail = $isExpectedThroughPostMail;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsExpectedThroughEmail(): ?bool
    {
        return $this->isExpectedThroughEmail;
    }

    /**
     * @param bool|null $isExpectedThroughEmail
     *
     * @return self
     */
    public function setIsExpectedThroughEmail(?bool $isExpectedThroughEmail): self
    {
        $this->isExpectedThroughEmail = $isExpectedThroughEmail;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsExcectedAtDelivery(): ?bool
    {
        return $this->isExcectedAtDelivery;
    }

    /**
     * @param bool|null $isExcectedAtDelivery
     *
     * @return self
     */
    public function setIsExcectedAtDelivery(?bool $isExcectedAtDelivery): self
    {
        $this->isExcectedAtDelivery = $isExcectedAtDelivery;

        return $this;
    }
}
