<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class RelPhoneNumber
{
    /**
     * @var string
     */
    protected $id;
    /**
     * Two letter country code.
     *
     * @var string
     */
    protected $countryCode;
    /**
     * The actual phonenumber formatted as E164.
     *
     * @var string
     */
    protected $number;
    /**
     * The actual phonenumber formatted as national number.
     *
     * @var string
     */
    protected $national;
    /**
     * @var string
     */
    protected $type;
    /**
     * @var \DateTime
     */
    protected $createdAt;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Two letter country code.
     */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * Two letter country code.
     */
    public function setCountryCode(?string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * The actual phonenumber formatted as E164.
     */
    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * The actual phonenumber formatted as E164.
     */
    public function setNumber(?string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * The actual phonenumber formatted as national number.
     */
    public function getNational(): ?string
    {
        return $this->national;
    }

    /**
     * The actual phonenumber formatted as national number.
     */
    public function setNational(?string $national): self
    {
        $this->national = $national;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}
