<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class RelVatRegistration
{
    /**
     * @var string
     */
    protected $countryCode;
    /**
     * @var string
     */
    protected $number;
    /**
     * @var RelVatRegistrationVerification
     */
    protected $verification;

    /**
     * @return string|null
     */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * @param string|null $countryCode
     *
     * @return self
     */
    public function setCountryCode(?string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getNumber(): ?string
    {
        return $this->number;
    }

    /**
     * @param string|null $number
     *
     * @return self
     */
    public function setNumber(?string $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * @return RelVatRegistrationVerification|null
     */
    public function getVerification(): ?RelVatRegistrationVerification
    {
        return $this->verification;
    }

    /**
     * @param RelVatRegistrationVerification|null $verification
     *
     * @return self
     */
    public function setVerification(?RelVatRegistrationVerification $verification): self
    {
        $this->verification = $verification;

        return $this;
    }
}
