<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class WmsProjection
{
    /**
     * @var WmsAvailableRoute[]
     */
    protected $routes;
    /**
     * @var WmsAvailableProjectionItem[]
     */
    protected $available;
    /**
     * @var WmsUnavailableProjectionItem[]
     */
    protected $unavailable;

    /**
     * @return WmsAvailableRoute[]|null
     */
    public function getRoutes(): ?array
    {
        return $this->routes;
    }

    /**
     * @param WmsAvailableRoute[]|null $routes
     */
    public function setRoutes(?array $routes): self
    {
        $this->routes = $routes;

        return $this;
    }

    /**
     * @return WmsAvailableProjectionItem[]|null
     */
    public function getAvailable(): ?array
    {
        return $this->available;
    }

    /**
     * @param WmsAvailableProjectionItem[]|null $available
     */
    public function setAvailable(?array $available): self
    {
        $this->available = $available;

        return $this;
    }

    /**
     * @return WmsUnavailableProjectionItem[]|null
     */
    public function getUnavailable(): ?array
    {
        return $this->unavailable;
    }

    /**
     * @param WmsUnavailableProjectionItem[]|null $unavailable
     */
    public function setUnavailable(?array $unavailable): self
    {
        $this->unavailable = $unavailable;

        return $this;
    }
}
