<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Afosto\Sdk\Model;

class WmsSort
{
    /**
     * @var string
     */
    protected $order;
    /**
     * @var string
     */
    protected $by;
    /**
     * @var string[]
     */
    protected $list;

    /**
     * @return string|null
     */
    public function getOrder(): ?string
    {
        return $this->order;
    }

    /**
     * @param string|null $order
     *
     * @return self
     */
    public function setOrder(?string $order): self
    {
        $this->order = $order;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getBy(): ?string
    {
        return $this->by;
    }

    /**
     * @param string|null $by
     *
     * @return self
     */
    public function setBy(?string $by): self
    {
        $this->by = $by;

        return $this;
    }

    /**
     * @return string[]|null
     */
    public function getList(): ?array
    {
        return $this->list;
    }

    /**
     * @param string[]|null $list
     *
     * @return self
     */
    public function setList(?array $list): self
    {
        $this->list = $list;

        return $this;
    }
}
